namespace ProjectEuler.Exercises
{
    public static class Exercise2
    {
        /*
         Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */
        public static void Run()
        {
            const int MAX_VALUE = 4000000;

            int number1 = 1;
            int number2 = 2;
            int aux;
            int result = 0;

            while (number2 < MAX_VALUE)
            {
                if (number1 % 2 == 0)
                    result += number1;

                if (number2 % 2 == 0)
                    result += number2;

                aux = number1 + number2;
                number1 = aux;
                aux = number1 + number2;
                number2 = aux;
            }

            Console.WriteLine("La suma de los multiplos es: " + result);
        }
    }
        
}
